name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-31:latest
    defaults:
      run:
        working-directory: API-Example
    steps:
      - uses: actions/checkout@v4
      - name: Fix Gradle mirror
        run: sed -i "s|http://mtl-gradle-mirror.oss-cn-hangzhou.aliyuncs.com/gradle-7.0.2-bin.zip|https://services.gradle.org/distributions/gradle-7.0.2-bin.zip|g" gradle/wrapper/gradle-wrapper.properties
      - name: Build APK
        run: |
          java -version
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: AliPlayer-APK
          path: API-Example/*/build/outputs/apk/debug/*.apk
